name: flashcards_flutter
version: 0.0.1
description: Flutter view of flashcards.

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'
  flutter: '>=0.1.4 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
# Localization
  flutter_localizations:
      sdk: flutter
  intl: "^0.15.4"
  intl_translation: "^0.16.4"

  cupertino_icons: '^0.1.0'
  flashcards_logic:
    path: ../logic

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
