name: flashcards_flutter
version: 0.0.1
description: Flutter view of flashcards.

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'
  flutter: '>=0.1.4 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: '^0.15.2'
  cupertino_icons: '^0.1.0'
  flashcards_common:
    path: ../common
  meta: '^1.1.2'
  cloud_firestore: '^0.3.2'
  firebase_auth: '^0.5.3'
  google_sign_in: '^3.0.0'
  flutter_markdown: '^0.1.5'
  url_launcher: '^3.0.0'
  package_info: '^0.3.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: '0.16.3'

flutter:
  uses-material-design: true
  fonts:
    - family: 'Lobster'
      fonts:
        - asset: assets/fonts/lobster-v20-latin-regular.ttf
          weight: 400
